### ISSUE TITLE
Responsiveness issue

### ISSUE THREAD

**Issue by 0sugo** [Elhambasir/capstone-project1--conference-page#3]
Great work on replicating the desired design! However, there seems to be an issue with the responsiveness of the website. The desktop version should kick in precisely at 768px to match the specified template. Currently, it is not functioning as in the guiding template. Achieving this would ensure consistent and optimal user experience across different devices and screen sizes.

**Comment by fickryiman** [comment]
awesome job, only need very small adjustment to add very top header for social media icons, and texts.
